# SPDX-License-Identifier: Apache-2.0
import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    String,
    Uuid,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from .base import PERMISSIONS, TRUSTS, Base, _check_values


class User(Base):
    """A human admitted to the system (gated by an owner invite). Holds accounts."""

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    google_sub: Mapped[str | None] = mapped_column(String, unique=True)
    label: Mapped[str | None] = mapped_column(String)
    is_owner: Mapped[bool] = mapped_column(default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Account(Base):
    """The access principal. A user self-provisions several (personal, work, ...)."""

    __tablename__ = "accounts"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"))
    label: Mapped[str | None] = mapped_column(String)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    # The account's OWN Person node (operator-profile B3): set on first global
    # preference write (auto-create) or by onboarding; the identity anchor for
    # global preferences. Distinguishes the operator's Person from other Person
    # nodes (family etc.) in the same personal space.
    person_node_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("nodes.id", ondelete="SET NULL", use_alter=True, name="fk_accounts_person_node")
    )


class Space(Base):
    """A named set of node references (not a container). Visibility unit."""

    __tablename__ = "spaces"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String)
    template: Mapped[str] = mapped_column(String, server_default="personal")
    write_floor: Mapped[str | None] = mapped_column(String)
    created_by: Mapped[uuid.UUID] = mapped_column(ForeignKey("accounts.id"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        CheckConstraint(
            "write_floor IS NULL OR write_floor IN ('allow', 'confirm', 'deny')",
            name="ck_spaces_write_floor",
        ),
    )


class Membership(Base):
    """(account, space) -> permission. Per-account, per-space."""

    __tablename__ = "memberships"

    account_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("accounts.id", ondelete="CASCADE"), primary_key=True
    )
    space_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("spaces.id", ondelete="CASCADE"), primary_key=True
    )
    permission: Mapped[str] = mapped_column(String)

    __table_args__ = (
        CheckConstraint(_check_values("permission", PERMISSIONS), name="ck_memberships_permission"),
    )


class Credential(Base):
    """An opaque bearer token for an LLM client, acting on behalf of one account."""

    __tablename__ = "credentials"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    account_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("accounts.id", ondelete="CASCADE"))
    token_hash: Mapped[str] = mapped_column(String, unique=True)
    label: Mapped[str | None] = mapped_column(String)
    trust: Mapped[str] = mapped_column(String, server_default="trusted")
    # Operator-profile E38: may THIS credential receive above-normal-sensitivity
    # preference content? Server-known, operator-set at issuance, default no —
    # never a caller-supplied claim (self-attestation is spoofable).
    sensitive_capable: Mapped[bool] = mapped_column(Boolean, server_default=text("false"))
    scopes: Mapped[list | None] = mapped_column(JSONB)
    allowed_tools: Mapped[list | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (CheckConstraint(_check_values("trust", TRUSTS), name="ck_credentials_trust"),)


class Invite(Base):
    """One-time system-admission link, generated by the owner, redeemed via OAuth."""

    __tablename__ = "invites"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    token_hash: Mapped[str] = mapped_column(String, unique=True)
    email: Mapped[str | None] = mapped_column(String)
    created_by: Mapped[uuid.UUID] = mapped_column(ForeignKey("accounts.id"))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    redeemed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    redeemed_by: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id"))
