# SPDX-License-Identifier: Apache-2.0
"""core graph identity policy schema

Revision ID: d8522fca4e80
Revises: 4777c754ce11
Create Date: 2026-06-29 22:04:41.753628

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d8522fca4e80"
down_revision: str | Sequence[str] | None = "4777c754ce11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edge_types",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), server_default="associative", nullable=False),
        sa.Column("sensitive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("src_types", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dst_types", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "category IN ('containment', 'associative')", name="ck_edge_types_category"
        ),
        sa.PrimaryKeyConstraint("type"),
    )
    op.create_table(
        "node_types",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("default_sensitivity", sa.String(), server_default="normal", nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("props_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "default_sensitivity IN ('low', 'normal', 'high', 'critical')",
            name="ck_node_types_sensitivity",
        ),
        sa.PrimaryKeyConstraint("type"),
    )
    op.create_table(
        "sensitivity_mode",
        sa.Column("sensitivity", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.CheckConstraint("mode IN ('allow', 'confirm', 'deny')", name="ck_sensmode_mode"),
        sa.CheckConstraint(
            "sensitivity IN ('low', 'normal', 'high', 'critical')", name="ck_sensmode_sensitivity"
        ),
        sa.PrimaryKeyConstraint("sensitivity", "operation"),
    )
    op.create_table(
        "template_floor",
        sa.Column("space_template", sa.String(), nullable=False),
        sa.Column("min_mode", sa.String(), nullable=False),
        sa.CheckConstraint(
            "min_mode IN ('allow', 'confirm', 'deny')", name="ck_templatefloor_mode"
        ),
        sa.PrimaryKeyConstraint("space_template"),
    )
    op.create_table(
        "trust_floor",
        sa.Column("client_trust", sa.String(), nullable=False),
        sa.Column("min_mode", sa.String(), nullable=False),
        sa.CheckConstraint("min_mode IN ('allow', 'confirm', 'deny')", name="ck_trustfloor_mode"),
        sa.PrimaryKeyConstraint("client_trust"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("google_sub", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("google_sub"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("trust", sa.String(), server_default="trusted", nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("allowed_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "trust IN ('trusted', 'limited', 'untrusted')", name="ck_credentials_trust"
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "invites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redeemed_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["redeemed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "spaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("template", sa.String(), server_default="personal", nullable=False),
        sa.Column("write_floor", sa.String(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "write_floor IS NULL OR write_floor IN ('allow', 'confirm', 'deny')",
            name="ck_spaces_write_floor",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memberships",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("permission", sa.String(), nullable=False),
        sa.CheckConstraint(
            "permission IN ('read', 'write', 'admin')", name="ck_memberships_permission"
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["space_id"], ["spaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id", "space_id"),
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("sensitivity", sa.String(), nullable=True),
        sa.Column("origin_space", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "sensitivity IS NULL OR sensitivity IN ('low', 'normal', 'high', 'critical')",
            name="ck_nodes_sensitivity",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["node_versions.id"],
            name="fk_nodes_current_version",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["origin_space"],
            ["spaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type"],
            ["node_types.type"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proposer_client", sa.Uuid(), nullable=True),
        sa.Column("op", sa.String(), nullable=False),
        sa.Column("target_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sensitivity", sa.String(), nullable=True),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("mode IN ('allow', 'confirm', 'deny')", name="ck_proposals_mode"),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'expired')", name="ck_proposals_status"
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposer_client"],
            ["credentials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("src_node", sa.Uuid(), nullable=False),
        sa.Column("dst_node", sa.Uuid(), nullable=False),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("sensitive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["dst_node"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["src_node"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["type"],
            ["edge_types.type"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_edges_dst_active",
        "edges",
        ["dst_node"],
        unique=False,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_index(
        "ix_edges_src_active",
        "edges",
        ["src_node"],
        unique=False,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_index(
        "uq_active_edge",
        "edges",
        ["type", "src_node", "dst_node"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_index(
        "uq_one_container",
        "edges",
        ["src_node"],
        unique=True,
        postgresql_where=sa.text("type = 'contained_in' AND valid_to IS NULL"),
    )
    op.create_table(
        "node_spaces",
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("added_by", sa.Uuid(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["space_id"], ["spaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("node_id", "space_id"),
    )
    op.create_table(
        "node_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_ref", sa.String(), nullable=True),
        sa.Column("author", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edge_spaces",
        sa.Column("edge_id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("added_by", sa.Uuid(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["edge_id"], ["edges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["space_id"], ["spaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("edge_id", "space_id"),
    )
    # Cyclic FK nodes.current_version_id -> node_versions.id: added explicitly after both
    # tables exist (op.create_table omits use_alter FKs).
    op.create_foreign_key(
        "fk_nodes_current_version", "nodes", "node_versions", ["current_version_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE nodes DROP CONSTRAINT IF EXISTS fk_nodes_current_version")
    op.drop_table("edge_spaces")
    op.drop_table("node_versions")
    op.drop_table("node_spaces")
    op.drop_index(
        "uq_one_container",
        table_name="edges",
        postgresql_where=sa.text("type = 'contained_in' AND valid_to IS NULL"),
    )
    op.drop_index(
        "uq_active_edge", table_name="edges", postgresql_where=sa.text("valid_to IS NULL")
    )
    op.drop_index(
        "ix_edges_src_active", table_name="edges", postgresql_where=sa.text("valid_to IS NULL")
    )
    op.drop_index(
        "ix_edges_dst_active", table_name="edges", postgresql_where=sa.text("valid_to IS NULL")
    )
    op.drop_table("edges")
    op.drop_table("proposals")
    op.drop_table("nodes")
    op.drop_table("memberships")
    op.drop_table("spaces")
    op.drop_table("invites")
    op.drop_table("credentials")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("trust_floor")
    op.drop_table("template_floor")
    op.drop_table("sensitivity_mode")
    op.drop_table("node_types")
    op.drop_table("edge_types")
    # ### end Alembic commands ###
